---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uproot-atlas
  namespace: servicex-uproot
spec:
  interval: 5m
  chart:
    spec:
      chart: servicex
      version: "v1.0.34"
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-uproot
      interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files

    objectStore:
      enabled: true
      internal: false
      publicURL: s3.ssl-hep.org
      useTLS: true
      useClientTLS: true

    # Settings for the Flask App
    app:
      adminEmail: fengping@uchicago.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.af.uchicago.edu
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        host: servicex.af.uchicago.edu
        tls:
          enabled: true
          host: uproot-atlas.servicex.af.uchicago.edu
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true
        image: sslhep/servicex-did-finder
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//

      CERNOpenData:
        enabled: true
        image: sslhep/servicex-did-finder-cernopendata
        # tag: develop
        pullPolicy: Always
    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot
      pullPolicy: Always

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      # defaultTransformerTag :20220311-2056-stable

    # enable postgresql backend for servicex
    postgres:
      enabled: true

    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the postgresql password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      primary:
        persistence:
          enabled: true
          storageClass: rook-ceph-block
      #  nodeSelector:
      #    storage: "rook"
      #    kernel-ml: "true"
      #    storage: "rook"
      existingSecret: servicex-secrets

      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password

    # Values for Minio Chart
    minio:
      auth:
        existingSecret: servicex-secrets

    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: xcache

    rbacEnabled: true

    ### secrets location
    secrets: servicex-secrets
