---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xaod
  namespace: servicex-xaod
spec:
  interval: 1m
  #serviceAccountName: servicex-testing-1
  chart:
    spec:
      chart: servicex
      version: '1.0.20'
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-xaod
      interval: 60m
#  valuesFrom:
#    - kind: ConfigMap
#      name: servicex-values
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      publicURL: xaod-minio.servicex.af.uchicago.edu
    
    
    # Settings for the Flask App
    app:
      adminEmail: fengping@uchicago.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.af.uchicago.edu
      # need dummy values so that it's in the config file 
      slackSigningSecret: "dummy1"
      newSignupWebhook: "dummy1"
      ingress:
        enabled: true
        host: servicex.af.uchicago.edu
        tls:
          enabled: true
          host: xaod.servicex.af.uchicago.edu
          clusterIssuer: letsencrypt-prod
      
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you 
    # change the rabbitmq password, otherwise the prior password will 
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: '9419'
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      #nodeselector: 
        #storage: rook
    
    # Settings for the DID Finder
    didFinder:
      rucio: 
        enabled: true
        image: sslhep/servicex-did-finder
        tag: develop
        pullPolicy: Always
        cachePrefix: root://192.170.227.122:1094/	
    
    # Settings for the preflight checker - this usually uses the same image as
    # the transformer
    preflight:
      image: sslhep/servicex_func_adl_xaod_transformer:develop
      pullPolicy: Always
    
    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_xaod
      # For uproot deployment
      # image: sslhep/servicex_code_gen_func_adl_uproot
      tag: develop
      pullPolicy: Always
    
    
    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_xaod_transformer:develop
      # For uproot deployment
      #  defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer:develop
    
    
    # enable postgresql backend for servicex
    postgres:
      enabled: true
    
    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you 
    # change the postgresql password, otherwise the prior password will 
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      #nodeSelector:
        #storage: "rook"
      persistence:
        enabled: true
        storageClass: rook-ceph-block
      #master:
      #  nodeSelector:
      #    kernel-ml: "true"
      #    storage: "rook"
      existingSecret: servicex-secrets
    
    # Values for Minio Chart
    minio:
      existingSecret: servicex-secrets
      persistence:
        enabled: true
        storageClass: local-storage 
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
        - "xaod-minio.servicex.af.uchicago.edu"
        tls:
        - hosts:
          - xaod-minio.servicex.af.uchicago.edu
          secretName: xaod-minio-tls
    
    
    ###### Settings for Authenticating with the CERN Infrastructure #######
    
    gridAccount: fehu
    
    rbacEnabled: true
    
    ### secrets location
    secrets: servicex-secrets
