---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xaod
  namespace: servicex-xaod
spec:
  interval: 5m
  chart:
    spec:
      chart: servicex
      version: "1.1.4"
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-xaod
      interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      internal: false
      publicURL: s3.ssl-hep.org
      useTLS: true
      useClientTLS: true

    logging:
      logstash:
        enabled: true
        host: servicex.atlas-ml.org
        port: 5959
        protocol: TCP

    # Settings for the Flask App
    app:
      adminEmail: fengping@uchicago.edu
      #       tag: develop
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.af.uchicago.edu
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy1"
      newSignupWebhook: "dummy1"
      ingress:
        enabled: true
        host: servicex.af.uchicago.edu
        tls:
          enabled: true
          host: xaod.servicex.af.uchicago.edu
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      # nodeselector:
      # storage: rook

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//
        servicex_latitude: 41.78
        servicex_longitude: -87.7
        memcache:
          enabled: true
          image: memcached
            # tag: alpine
          ttl: 86400  
      CERNOpenData:
        enabled: false
        image: sslhep/servicex-did-finder-cernopendata
        pullPolicy: Always
    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_atlas_xaod
      defaultScienceContainerImage: sslhep/sslhep/servicex_func_adl_xaod_transformer
      defaultScienceContainerTag: v1.1.4
      pullPolicy: Always

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      # Settings for the uproot transformer science container
      language: bash
      exec: /generated/transform_single_file.sh

    # enable postgresql backend for servicex
    postgres:
      enabled: true

    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the postgresql password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      primary:
        resources:
          requests:
            cpu: 8
        persistence:
          enabled: true
          storageClass: rook-ceph-block
      #  nodeSelector:
      #    storage: "rook"
      #    kernel-ml: "true"
      #    storage: "rook"
      existingSecret: servicex-secrets

      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password

    # Values for Minio Chart
    minio:
      auth:
        existingSecret: servicex-secrets

      # tls:
      #   enabled: false
      # service:
      #   ports:
      #     api: 9000

      # persistence:
      #   enabled: true
      #   storageClass: local-storage
      #   # storageClass: rook-ceph-block

      # ingress:
      #   enabled: true
      #   tls: true
      #   annotations:
      #     kubernetes.io/ingress.class: nginx
      #     cert-manager.io/cluster-issuer: letsencrypt-prod
      #     acme.cert-manager.io/http01-edit-in-place: "true"
      #   hostname: "xaod-minio-console.servicex.af.uchicago.edu"

      # apiIngress:
      #   enabled: true
      #   tls: true
      #   annotations:
      #     kubernetes.io/ingress.class: nginx
      #     cert-manager.io/cluster-issuer: letsencrypt-prod
      #     acme.cert-manager.io/http01-edit-in-place: "true"
      #   hostname: "xaod-minio.servicex.af.uchicago.edu"


    # Values for the Minio cleanup
    # run once every 8 hours and prune storage to 1T if more than 1.5T is being
    # used
    # files more than 30 days old get removed
    minioCleanup:
      enabled: true
      schedule: "0 */8 * * *"
      maxAge: 30
      maxSize: "1500G"
      normSize: "1T"

    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: xcache

    rbacEnabled: true

    ### secrets location
    secrets: servicex-secrets
